networks:
  default:
    external: true
    name: "${DEFAULT_NETWORK}"

services:
  reverse-proxy:
    build:
      context: .
      dockerfile: proxy/Dockerfile
    container_name: reverse-proxy
    environment:
      - SELECTED_APPS=${SELECTED_APPS}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default