networks:
  default:
    external: true
    name: "${DEFAULT_NETWORK}"

services:
    fe:
        build:
          context: .
          dockerfile: node/Dockerfile
        container_name: "${DOCKER_COMPOSE_ENV}-fe"
        restart: on-failure
        volumes:
          - ../fe:/home/node/app
        ports:
          - "5173:5173"
        networks:
          - default